export const SIGNUP = "SIGNUP";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VIEW_ALL_COMPANIES = "VIEW_ALL_COMPANIES";
export const VIEW_ALL_COMPANIES_SUCCESS = "VIEW_ALL_COMPANIES_SUCCESS";
export const VIEW_ALL_COMPANIES_FAILURE = "VIEW_ALL_COMPANIES_FAILURE";

export const VIEW_ALL_STUDENTS = "VIEW_ALL_STUDENTS";
export const VIEW_ALL_STUDENTS_SUCCESS = "VIEW_ALL_STUDENTS_SUCCESS";
export const VIEW_ALL_STUDENTS_FAILURE = "VIEW_ALL_STUDENTS_FAILURE";

export const VIEW_ALL_PROJECTS = "VIEW_ALL_PROJECTS";
export const VIEW_ALL_PROJECTS_SUCCESS = "VIEW_ALL_PROJECTS_SUCCESS";
export const VIEW_ALL_PROJECTS_FAILURE = "VIEW_ALL_PROJECTS_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const APPLIED_POST = "APPLIED_POST";
export const APPLIED_POST_SUCCESS = "APPLIED_POST_SUCCESS";
export const APPLIED_POST_FAILURE = "APPLIED_POST_FAILURE";

export const ADD_POST = "ADD_POST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";
